### ISSUE TITLE
[FEAT 👩‍💻] 전반적인 환경 설정

### ISSUE THREAD

**Issue by yu-heejin** [kotlin-project-team/backend#2]
## Description ✏️
* 프로젝트 구조를 전반적으로 수정합니다.
## Todo
- [x] config private submodule 연동하기
- [ ] 실행 스크립트 파일 추가
- [ ] 멀티 모듈 마이그레이션
- [ ] Docker 파일 추가
