### ISSUE TITLE
[REF 👩‍💻] 댓글 리팩토링 및 코드 정리

### ISSUE THREAD

**Issue by devyubin** [kotlin-project-team/backend#51]
## Description ✏️
- 전반적으로 코드 정리 및 리팩토링이 필요한 부분을 수정합니다.
## Todo
- [ ] 코드 전체 점검
- [x] 주석 및 필요없는 코드 삭제
- [ ] 예외처리 확인
- [x] 무한스크롤 문제 수정
